import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  const AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const _strings = <String, Map<String, String>>{
    'en': {
      'appName': 'ordo',
      'settings': 'Settings',
      'support': 'Support',
      'buyMeACoffee': 'Buy me a coffee',
      'data': 'Data',
      'dataExport': 'Data Export',
      'dataImport': 'Data Import',
      'preferences': 'Preferences',
      'darkTheme': 'Dark theme',
      'notifications': 'Notifications',
      'taskReminders': 'Task reminders',
      'separateSendButton': 'Separate send button',
      'swipeToDelete': 'Swipe to delete',
      'compactCards': 'Compact cards',
      'amoledMode': 'AMOLED mode',
      'dynamicColor': 'Dynamic color',
      'specialTheme': 'Special theme',
      'skipWelcome': 'Skip welcome',
      'deleteAllData': 'Delete all data',
      'deleteAllDataSubtitle': 'Permanently erase all notes and tasks',
      'language': 'Language',
      'system': 'System',
      'english': 'English',
      'arabic': 'العربية',
      'notes': 'notes',
      'tasks': 'tasks',
      'chat': 'Chat',
      'typeAMessage': 'Type a message...',
      'send': 'Send',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'ok': 'OK',
      'home': 'Home',
      'noChatsYet': 'No chats yet',
      'newChat': 'New chat',
      'dangerZone': 'Danger Zone',
      'reportAnIssue': 'Report an issue',
      'delete': 'Delete',
      'allDataDeleted': 'All data deleted.',
      'failedToExportData': 'Failed to export data',
      'importDataTitle': 'Import data?',
      'importDataMessage': 'This will add messages from a previously exported file to your current chat.',
      'importLabel': 'Import',
      'dataImportedSuccessfully': 'Data imported successfully',
      'noExportFileFound': 'No export file found',
      'failedToImportData': 'Failed to import data',
      'hexagonalButtonNextToBox': 'Hexagonal button next to box',
      'buttonInsideComposeBox': 'Button inside compose box',
      'swipeCardsToDelete': 'Swipe cards to delete',
      'longPressForActions': 'Long-press for actions',
      'hideIconsOnNoteTaskCards': 'Hide icons on note/task cards',
      'showIconsOnNoteTaskCards': 'Show icons on note/task cards',
      'trueBlackBackground': 'True black background',
      'useWallpaperColors': 'Use wallpaper colors',
      'customColorScheme': 'Custom color scheme',
      'goDirectlyToHomeOnLaunch': 'Go directly to home on launch',
      'checkForUpdates': 'Check for updates',
      'checkingForUpdates': 'Checking for updates...',
      'failedToCheckForUpdates': 'Failed to check for updates',
      'download': 'Download',
      'youAreUsingLatestVersion': 'You are using the latest version',
      'joinTelegramGroup': 'Join Telegram group',
      'getSupportAndUpdates': 'Get support and updates',
      'supportTheDeveloper': 'Support the developer',
      'suggestAFeature': 'Suggest a feature',
      'deleteAllDataConfirmation': 'This action cannot be undone. All your thoughts and tasks will be permanently removed.',
      'myOrdoData': 'My Ordo Data',
      'updateAvailable': 'Update',
      'from': 'from',
      'craftedBy': 'Crafted by',
      'madeInLibya': 'Made in Libya',
      'softwareDeveloperBuildingOrdo': 'Software developer building Ordo.',
      'gitHubProfile': 'GitHub Profile',
      'chats': 'Chats',
      'deleteChatTitle': 'Delete chat?',
      'deleteChatMessage': 'This will permanently delete this chat and all its messages.',
      'startNewConversationHint': 'Start a new conversation\nby tapping the button below',
      'justNow': 'Just now',
      'minutesAgo': '{minutes}m ago',
      'hoursAgo': '{hours}h ago',
      'daysAgo': '{days}d ago',
      'active': 'Active',
      'deleteChatTooltip': 'Delete chat',
      'deleteThoughtTitle': 'Delete thought?',
      'deleteThoughtMessage': 'This action cannot be undone.',
      'editThought': 'Edit thought',
      'save': 'Save',
      'markIncomplete': 'Mark incomplete',
      'markComplete': 'Mark complete',
      'setReminder': 'Set reminder',
      'copyText': 'Copy text',
      'labelTask': 'TASK',
      'labelNote': 'NOTE',
      'emptySpaceTitle': 'Your space is empty',
      'emptySpaceMessage': 'Type a note or a task below and press send to get started.',
      'typeThoughtHint': 'Type a thought...',
      'addTaskHint': 'Add a task...',
      'enterChatNameHint': 'Enter chat name...',
      'suggestions': 'Suggestions',
      'createChat': 'Create Chat',
      'setReminderTitle': 'Set Reminder',
      'setReminderMessage': 'Choose when you want to be reminded about this task',
      'skip': 'Skip',
      'setReminderButton': 'Set Reminder',
      'suggestionMyThoughts': 'My Thoughts',
      'suggestionDailyTasks': 'Daily Tasks',
      'suggestionProjectIdeas': 'Project Ideas',
      'suggestionPersonalNotes': 'Personal Notes',
      'suggestionWorkJournal': 'Work Journal',
    },
    'ar': {
      'appName': 'أوردو',
      'settings': 'الإعدادات',
      'support': 'الدعم',
      'buyMeACoffee': 'اشتر لي قهوة',
      'data': 'البيانات',
      'dataExport': 'تصدير البيانات',
      'dataImport': 'استيراد البيانات',
      'preferences': 'التفضيلات',
      'darkTheme': 'الوضع الداكن',
      'notifications': 'الإشعارات',
      'taskReminders': 'تذكير المهام',
      'separateSendButton': 'زر إرسال منفصل',
      'swipeToDelete': 'التمرير للحذف',
      'compactCards': 'بطاقات مضغوطة',
      'amoledMode': 'وضع AMOLED',
      'dynamicColor': 'الألوان الديناميكية',
      'specialTheme': 'ثيم خاص',
      'skipWelcome': 'تخطي الترحيب',
      'deleteAllData': 'حذف جميع البيانات',
      'deleteAllDataSubtitle': 'مسح جميع الملاحظات والمهام نهائياً',
      'language': 'اللغة',
      'system': 'النظام',
      'english': 'English',
      'arabic': 'العربية',
      'notes': 'ملاحظات',
      'tasks': 'مهام',
      'chat': 'محادثة',
      'typeAMessage': 'اكتب رسالة...',
      'send': 'إرسال',
      'cancel': 'إلغاء',
      'confirm': 'تأكيد',
      'ok': 'حسناً',
      'home': 'الرئيسية',
      'noChatsYet': 'لا توجد محادثات بعد',
      'newChat': 'محادثة جديدة',
      'dangerZone': 'المنطقة الخطرة',
      'reportAnIssue': 'الإبلاغ عن مشكلة',
      'delete': 'حذف',
      'allDataDeleted': 'تم حذف جميع البيانات.',
      'failedToExportData': 'فشل تصدير البيانات',
      'importDataTitle': 'استيراد البيانات؟',
      'importDataMessage': 'سيؤدي هذا إلى إضافة رسائل من ملف تم تصديره سابقاً إلى محادثتك الحالية.',
      'importLabel': 'استيراد',
      'dataImportedSuccessfully': 'تم استيراد البيانات بنجاح',
      'noExportFileFound': 'لم يتم العثور على ملف تصدير',
      'failedToImportData': 'فشل استيراد البيانات',
      'hexagonalButtonNextToBox': 'زر على شكل سداسي بجانب المربع',
      'buttonInsideComposeBox': 'زر داخل مربع الكتابة',
      'swipeCardsToDelete': 'اسحب البطاقات للحذف',
      'longPressForActions': 'اضغط مطولاً للإجراءات',
      'hideIconsOnNoteTaskCards': 'إخفاء الأيقونات على بطاقات الملاحظات/المهام',
      'showIconsOnNoteTaskCards': 'إظهار الأيقونات على بطاقات الملاحظات/المهام',
      'trueBlackBackground': 'خلفية سوداء حقيقية',
      'useWallpaperColors': 'استخدام ألوان الخلفية',
      'customColorScheme': 'نظام ألوان مخصص',
      'goDirectlyToHomeOnLaunch': 'الانتقال مباشرة للرئيسية عند التشغيل',
      'checkForUpdates': 'التحقق من التحديثات',
      'checkingForUpdates': 'جارٍ التحقق من التحديثات...',
      'failedToCheckForUpdates': 'فشل التحقق من التحديثات',
      'download': 'تنزيل',
      'youAreUsingLatestVersion': 'أنت تستخدم أحدث إصدار',
      'joinTelegramGroup': 'انضم إلى مجموعة تيليغرام',
      'getSupportAndUpdates': 'احصل على الدعم والتحديثات',
      'supportTheDeveloper': 'ادعم المطور',
      'suggestAFeature': 'اقترح ميزة',
      'deleteAllDataConfirmation': 'لا يمكن التراجع عن هذا الإجراء. سيتم حذف جميع أفكارك ومهامك بشكل دائم.',
      'myOrdoData': 'بيانات أوردو الخاصة بي',
      'updateAvailable': 'تحديث',
      'from': 'من',
      'craftedBy': 'صنع بواسطة',
      'madeInLibya': 'من ليبيا',
      'softwareDeveloperBuildingOrdo': 'مطور برمجيات يبني أوردو.',
      'gitHubProfile': 'ملف GitHub',
      'chats': 'المحادثات',
      'deleteChatTitle': 'حذف المحادثة؟',
      'deleteChatMessage': 'سيؤدي هذا إلى حذف هذه المحادثة وجميع رسائلها بشكل دائم.',
      'startNewConversationHint': 'ابدأ محادثة جديدة\nبالنقر على الزر أدناه',
      'justNow': 'للتو',
      'minutesAgo': 'منذ {minutes} دقيقة',
      'hoursAgo': 'منذ {hours} ساعة',
      'daysAgo': 'منذ {days} يوم',
      'active': 'نشط',
      'deleteChatTooltip': 'حذف المحادثة',
      'deleteThoughtTitle': 'حذف الفكرة؟',
      'deleteThoughtMessage': 'لا يمكن التراجع عن هذا الإجراء.',
      'editThought': 'تعديل الفكرة',
      'save': 'حفظ',
      'markIncomplete': 'تحديد غير مكتمل',
      'markComplete': 'تحديد مكتمل',
      'setReminder': 'تعيين تذكير',
      'copyText': 'نسخ النص',
      'labelTask': 'مهمة',
      'labelNote': 'ملاحظة',
      'emptySpaceTitle': 'مساحتك فارغة',
      'emptySpaceMessage': 'اكتب ملاحظة أو مهمة أدناه واضغط إرسال للبدء.',
      'typeThoughtHint': 'اكتب فكرة...',
      'addTaskHint': 'أضف مهمة...',
      'enterChatNameHint': 'أدخل اسم المحادثة...',
      'suggestions': 'اقتراحات',
      'createChat': 'إنشاء محادثة',
      'setReminderTitle': 'تعيين تذكير',
      'setReminderMessage': 'اختر الوقت الذي تريد أن يتم تذكيرك فيه بهذه المهمة',
      'skip': 'تخطي',
      'setReminderButton': 'تعيين تذكير',
      'suggestionMyThoughts': 'أفكاري',
      'suggestionDailyTasks': 'المهام اليومية',
      'suggestionProjectIdeas': 'أفكار المشاريع',
      'suggestionPersonalNotes': 'ملاحظات شخصية',
      'suggestionWorkJournal': 'مذكرات العمل',
    },
    'ru': {
      'appName': 'ordo',
      'settings': 'Настройки',
      'support': 'Поддержка',
      'buyMeACoffee': 'Купи мне кофе',
      'data': 'Данные',
      'dataExport': 'Экспорт данных',
      'dataImport': 'Импорт данных',
      'preferences': 'Настройки',
      'darkTheme': 'Тёмная тема',
      'notifications': 'Уведомления',
      'taskReminders': 'Напоминания о задачах',
      'separateSendButton': 'Отдельная кнопка отправки',
      'swipeToDelete': 'Смахивание для удаления',
      'compactCards': 'Компактные карточки',
      'amoledMode': 'Режим AMOLED',
      'dynamicColor': 'Динамический цвет',
      'specialTheme': 'Особая тема',
      'skipWelcome': 'Пропустить приветствие',
      'deleteAllData': 'Удалить все данные',
      'deleteAllDataSubtitle': 'Навсегда удалить все заметки и задачи',
      'language': 'Язык',
      'system': 'Система',
      'english': 'English',
      'arabic': 'العربية',
      'notes': 'заметки',
      'tasks': 'задачи',
      'chat': 'Чат',
      'typeAMessage': 'Напишите сообщение...',
      'send': 'Отправить',
      'cancel': 'Отмена',
      'confirm': 'Подтвердить',
      'ok': 'OK',
      'home': 'Главная',
      'noChatsYet': 'Чатов пока нет',
      'newChat': 'Новый чат',
      'dangerZone': 'Опасная зона',
      'reportAnIssue': 'Сообщить о проблеме',
      'delete': 'Удалить',
      'allDataDeleted': 'Все данные удалены.',
      'failedToExportData': 'Не удалось экспортировать данные',
      'importDataTitle': 'Импортировать данные?',
      'importDataMessage': 'Это добавит сообщения из ранее экспортированного файла в ваш текущий чат.',
      'importLabel': 'Импорт',
      'dataImportedSuccessfully': 'Данные успешно импортированы',
      'noExportFileFound': 'Файл экспорта не найден',
      'failedToImportData': 'Не удалось импортировать данные',
      'hexagonalButtonNextToBox': 'Шестиугольная кнопка рядом с полем',
      'buttonInsideComposeBox': 'Кнопка внутри поля ввода',
      'swipeCardsToDelete': 'Смахните карточки для удаления',
      'longPressForActions': 'Долгое нажатие для действий',
      'hideIconsOnNoteTaskCards': 'Скрыть иконки на карточках заметок/задач',
      'showIconsOnNoteTaskCards': 'Показать иконки на карточках заметок/задач',
      'trueBlackBackground': 'Настоящий чёрный фон',
      'useWallpaperColors': 'Использовать цвета обоев',
      'customColorScheme': 'Пользовательская цветовая схема',
      'goDirectlyToHomeOnLaunch': 'Перейти сразу на главную при запуске',
      'checkForUpdates': 'Проверить обновления',
      'checkingForUpdates': 'Проверка обновлений...',
      'failedToCheckForUpdates': 'Не удалось проверить обновления',
      'download': 'Скачать',
      'youAreUsingLatestVersion': 'Вы используете последнюю версию',
      'joinTelegramGroup': 'Присоединиться к Telegram',
      'getSupportAndUpdates': 'Получить поддержку и обновления',
      'supportTheDeveloper': 'Поддержать разработчика',
      'suggestAFeature': 'Предложить функцию',
      'deleteAllDataConfirmation': 'Это действие нельзя отменить. Все ваши мысли и задачи будут удалены навсегда.',
      'myOrdoData': 'Мои данные Ordo',
      'updateAvailable': 'Обновить',
      'from': 'от',
      'craftedBy': 'Создано',
      'madeInLibya': 'Сделано в Ливии',
      'softwareDeveloperBuildingOrdo': 'Разработчик, создающий Ordo.',
      'gitHubProfile': 'Профиль GitHub',
      'chats': 'Чаты',
      'deleteChatTitle': 'Удалить чат?',
      'deleteChatMessage': 'Это навсегда удалит этот чат и все его сообщения.',
      'startNewConversationHint': 'Начните новый разговор\nнажав на кнопку ниже',
      'justNow': 'Только что',
      'minutesAgo': '{minutes}м назад',
      'hoursAgo': '{hours}ч назад',
      'daysAgo': '{days}д назад',
      'active': 'Активен',
      'deleteChatTooltip': 'Удалить чат',
      'deleteThoughtTitle': 'Удалить мысль?',
      'deleteThoughtMessage': 'Это действие нельзя отменить.',
      'editThought': 'Редактировать мысль',
      'save': 'Сохранить',
      'markIncomplete': 'Отметить как невыполненное',
      'markComplete': 'Отметить как выполненное',
      'setReminder': 'Установить напоминание',
      'copyText': 'Копировать текст',
      'labelTask': 'ЗАДАЧА',
      'labelNote': 'ЗАМЕТКА',
      'emptySpaceTitle': 'Ваше пространство пусто',
      'emptySpaceMessage': 'Напишите заметку или задачу ниже и нажмите отправить, чтобы начать.',
      'typeThoughtHint': 'Напишите мысль...',
      'addTaskHint': 'Добавьте задачу...',
      'enterChatNameHint': 'Введите название чата...',
      'suggestions': 'Предложения',
      'createChat': 'Создать чат',
      'setReminderTitle': 'Установить напоминание',
      'setReminderMessage': 'Выберите время, когда вы хотите получить напоминание о этой задаче',
      'skip': 'Пропустить',
      'setReminderButton': 'Установить напоминание',
      'suggestionMyThoughts': 'Мои мысли',
      'suggestionDailyTasks': 'Ежедневные задачи',
      'suggestionProjectIdeas': 'Идеи проектов',
      'suggestionPersonalNotes': 'Личные заметки',
      'suggestionWorkJournal': 'Рабочий журнал',
    },
    'ko': {
      'appName': 'ordo',
      'settings': '설정',
      'support': '지원',
      'buyMeACoffee': '커피 한 잔 사주기',
      'data': '데이터',
      'dataExport': '데이터 내보내기',
      'dataImport': '데이터 가져오기',
      'preferences': '환경 설정',
      'darkTheme': '다크 테마',
      'notifications': '알림',
      'taskReminders': '작업 알림',
      'separateSendButton': '별도 전송 버튼',
      'swipeToDelete': '스와이프하여 삭제',
      'compactCards': '간편 카드',
      'amoledMode': 'AMOLED 모드',
      'dynamicColor': '다이내믹 색상',
      'specialTheme': '특별 테마',
      'skipWelcome': '환영 건너뛰기',
      'deleteAllData': '모든 데이터 삭제',
      'deleteAllDataSubtitle': '모든 노트와 작업을 영구적으로 삭제',
      'language': '언어',
      'system': '시스템',
      'english': 'English',
      'arabic': 'العربية',
      'notes': '노트',
      'tasks': '작업',
      'chat': '채팅',
      'typeAMessage': '메시지를 입력하세요...',
      'send': '전송',
      'cancel': '취소',
      'confirm': '확인',
      'ok': '확인',
      'home': '홈',
      'noChatsYet': '아직 채팅이 없습니다',
      'newChat': '새 채팅',
      'dangerZone': '위험 구역',
      'reportAnIssue': '문제 신고',
      'delete': '삭제',
      'allDataDeleted': '모든 데이터가 삭제되었습니다.',
      'failedToExportData': '데이터 내보내기 실패',
      'importDataTitle': '데이터를 가져올까요?',
      'importDataMessage': '이전에 내보낸 파일의 메시지를 현재 채팅에 추가합니다.',
      'importLabel': '가져오기',
      'dataImportedSuccessfully': '데이터를 성공적으로 가져왔습니다',
      'noExportFileFound': '내보내기 파일을 찾을 수 없습니다',
      'failedToImportData': '데이터 가져오기 실패',
      'hexagonalButtonNextToBox': '입력창 옆 육각형 버튼',
      'buttonInsideComposeBox': '입력창 내부 버튼',
      'swipeCardsToDelete': '카드를 스와이프하여 삭제',
      'longPressForActions': '길게 눌러 작업',
      'hideIconsOnNoteTaskCards': '노트/작업 카드 아이콘 숨기기',
      'showIconsOnNoteTaskCards': '노트/작업 카드 아이콘 표시',
      'trueBlackBackground': '완전 검은 배경',
      'useWallpaperColors': '배경화면 색상 사용',
      'customColorScheme': '사용자 정의 색상',
      'goDirectlyToHomeOnLaunch': '시작 시 바로 홈으로 이동',
      'checkForUpdates': '업데이트 확인',
      'checkingForUpdates': '업데이트 확인 중...',
      'failedToCheckForUpdates': '업데이트 확인 실패',
      'download': '다운로드',
      'youAreUsingLatestVersion': '최신 버전을 사용 중입니다',
      'joinTelegramGroup': 'Telegram 그룹 가입',
      'getSupportAndUpdates': '지원 및 업데이트 받기',
      'supportTheDeveloper': '개발자 지원하기',
      'suggestAFeature': '기능 제안',
      'deleteAllDataConfirmation': '이 작업은 취소할 수 없습니다. 모든 생각과 작업이 영구적으로 삭제됩니다.',
      'myOrdoData': '내 Ordo 데이터',
      'updateAvailable': '업데이트',
      'from': '만든 이',
      'craftedBy': '제작',
      'madeInLibya': '리비아에서 제작',
      'softwareDeveloperBuildingOrdo': 'Ordo를 만드는 소프트웨어 개발자.',
      'gitHubProfile': 'GitHub 프로필',
      'chats': '채팅',
      'deleteChatTitle': '채팅을 삭제할까요?',
      'deleteChatMessage': '이 채팅과 모든 메시지가 영구적으로 삭제됩니다.',
      'startNewConversationHint': '아래 버튼을 눌러\n새 대화를 시작하세요',
      'justNow': '방금',
      'minutesAgo': '{minutes}분 전',
      'hoursAgo': '{minutes}시간 전',
      'daysAgo': '{days}일 전',
      'active': '활성',
      'deleteChatTooltip': '채팅 삭제',
      'deleteThoughtTitle': '생각을 삭제할까요?',
      'deleteThoughtMessage': '이 작업은 취소할 수 없습니다.',
      'editThought': '생각 수정',
      'save': '저장',
      'markIncomplete': '미완료로 표시',
      'markComplete': '완료로 표시',
      'setReminder': '알림 설정',
      'copyText': '텍스트 복사',
      'labelTask': '작업',
      'labelNote': '노트',
      'emptySpaceTitle': '공간이 비어 있습니다',
      'emptySpaceMessage': '아래에 노트나 작업을 입력하고 전송을 눌러 시작하세요.',
      'typeThoughtHint': '생각을 입력하세요...',
      'addTaskHint': '작업을 추가하세요...',
      'enterChatNameHint': '채팅 이름을 입력하세요...',
      'suggestions': '추천',
      'createChat': '채팅 만들기',
      'setReminderTitle': '알림 설정',
      'setReminderMessage': '이 작업에 대해 알림을 받을 시간을 선택하세요',
      'skip': '건너뛰기',
      'setReminderButton': '알림 설정',
      'suggestionMyThoughts': '내 생각',
      'suggestionDailyTasks': '일일 작업',
      'suggestionProjectIdeas': '프로젝트 아이디어',
      'suggestionPersonalNotes': '개인 노트',
      'suggestionWorkJournal': '업무 일지',
    },
    'fa': {
      'appName': 'ordo',
      'settings': 'تنظیمات',
      'support': 'پشتیبانی',
      'buyMeACoffee': 'برام قهوه بخر',
      'data': 'داده‌ها',
      'dataExport': 'خروجی داده',
      'dataImport': 'ورودی داده',
      'preferences': 'تنظیمات',
      'darkTheme': 'حالت تاریک',
      'notifications': 'اعلان‌ها',
      'taskReminders': 'یادآوری وظایف',
      'separateSendButton': 'دکمه ارسال مجزا',
      'swipeToDelete': 'کشیدن برای حذف',
      'compactCards': 'کارت‌های فشرده',
      'amoledMode': 'حالت AMOLED',
      'dynamicColor': 'رنگ پویا',
      'specialTheme': 'تم ویژه',
      'skipWelcome': 'رد خوش‌آمدگویی',
      'deleteAllData': 'حذف همه داده‌ها',
      'deleteAllDataSubtitle': 'حذف دائمی همه یادداشت‌ها و وظایف',
      'language': 'زبان',
      'system': 'سیستم',
      'english': 'English',
      'arabic': 'العربية',
      'notes': 'یادداشت',
      'tasks': 'وظایف',
      'chat': 'گفتگو',
      'typeAMessage': 'پیام بنویسید...',
      'send': 'ارسال',
      'cancel': 'لغو',
      'confirm': 'تأیید',
      'ok': 'باشه',
      'home': 'خانه',
      'noChatsYet': 'هنوز گفتگویی نیست',
      'newChat': 'گفتگوی جدید',
      'dangerZone': 'منطقه خطر',
      'reportAnIssue': 'گزارش مشکل',
      'delete': 'حذف',
      'allDataDeleted': 'همه داده‌ها حذف شدند.',
      'failedToExportData': 'خروجی داده ناموفق بود',
      'importDataTitle': 'ورودی داده‌ها؟',
      'importDataMessage': 'این کار پیام‌ها را از فایل خروجی قبلی به گفتگوی فعلی اضافه می‌کند.',
      'importLabel': 'ورودی',
      'dataImportedSuccessfully': 'داده‌ها با موفقیت وارد شدند',
      'noExportFileFound': 'فایل خروجی یافت نشد',
      'failedToImportData': 'ورودی داده ناموفق بود',
      'hexagonalButtonNextToBox': 'دکمه شش‌گوش کنار جعبه',
      'buttonInsideComposeBox': 'دکمه داخل جعبه نوشتن',
      'swipeCardsToDelete': 'کارت‌ها را بکشید تا حذف شوند',
      'longPressForActions': 'فشار طولانی برای اقدامات',
      'hideIconsOnNoteTaskCards': 'مخفی کردن آیکون‌ها روی کارت‌های یادداشت/وظیفه',
      'showIconsOnNoteTaskCards': 'نمایش آیکون‌ها روی کارت‌های یادداشت/وظیفه',
      'trueBlackBackground': 'پس‌زمینه کاملاً سیاه',
      'useWallpaperColors': 'استفاده از رنگ‌های والپیپر',
      'customColorScheme': 'طرح رنگ سفارشی',
      'goDirectlyToHomeOnLaunch': 'رفتن مستقیم به خانه هنگام راه‌اندازی',
      'checkForUpdates': 'بررسی به‌روزرسانی',
      'checkingForUpdates': 'در حال بررسی به‌روزرسانی...',
      'failedToCheckForUpdates': 'بررسی به‌روزرسانی ناموفق بود',
      'download': 'دانلود',
      'youAreUsingLatestVersion': 'شما از آخرین نسخه استفاده می‌کنید',
      'joinTelegramGroup': 'عضویت در گروه تلگرام',
      'getSupportAndUpdates': 'دریافت پشتیبانی و به‌روزرسانی',
      'supportTheDeveloper': 'حمایت از توسعه‌دهنده',
      'suggestAFeature': 'پیشنهاد ویژگی',
      'deleteAllDataConfirmation': 'این عمل قابل بازگشت نیست. همه افکار و وظایف شما به طور دائمی حذف خواهند شد.',
      'myOrdoData': 'داده‌های Ordo من',
      'updateAvailable': 'به‌روزرسانی',
      'from': 'از',
      'craftedBy': 'ساخته شده توسط',
      'madeInLibya': 'ساخته شده در لیبی',
      'softwareDeveloperBuildingOrdo': 'توسعه‌دهنده نرم‌افزار در حال ساخت Ordo.',
      'gitHubProfile': 'پروفایل GitHub',
      'chats': 'گفتگوها',
      'deleteChatTitle': 'حذف گفتگو؟',
      'deleteChatMessage': 'این کار این گفتگو و همه پیام‌های آن را برای همیشه حذف می‌کند.',
      'startNewConversationHint': 'یک گفتگوی جدید شروع کنید\nبا زدن دکمه زیر',
      'justNow': 'همین الان',
      'minutesAgo': '{minutes}د پیش',
      'hoursAgo': '{hours}س پیش',
      'daysAgo': '{days}ر پیش',
      'active': 'فعال',
      'deleteChatTooltip': 'حذف گفتگو',
      'deleteThoughtTitle': 'حذف فکر؟',
      'deleteThoughtMessage': 'این عمل قابل بازگشت نیست.',
      'editThought': 'ویرایش فکر',
      'save': 'ذخیره',
      'markIncomplete': 'علامت‌گذاری به عنوان ناقص',
      'markComplete': 'علامت‌گذاری به عنوان کامل',
      'setReminder': 'تنظیم یادآوری',
      'copyText': 'کپی متن',
      'labelTask': 'وظیفه',
      'labelNote': 'یادداشت',
      'emptySpaceTitle': 'فضای شما خالی است',
      'emptySpaceMessage': 'یک یادداشت یا وظیفه در زیر بنویسید و ارسال را بزنید تا شروع کنید.',
      'typeThoughtHint': 'یک فکر بنویسید...',
      'addTaskHint': 'یک وظیفه اضافه کنید...',
      'enterChatNameHint': 'نام گفتگو را وارد کنید...',
      'suggestions': 'پیشنهادها',
      'createChat': 'ایجاد گفتگو',
      'setReminderTitle': 'تنظیم یادآوری',
      'setReminderMessage': 'زمانی را که می‌خواهید برای این وظیفه یادآوری شوید انتخاب کنید',
      'skip': 'رد کردن',
      'setReminderButton': 'تنظیم یادآوری',
      'suggestionMyThoughts': 'افکار من',
      'suggestionDailyTasks': 'وظایف روزانه',
      'suggestionProjectIdeas': 'ایده‌های پروژه',
      'suggestionPersonalNotes': 'یادداشت‌های شخصی',
      'suggestionWorkJournal': 'دفترچه کار',
    },
    'es': {
      'appName': 'ordo',
      'settings': 'Ajustes',
      'support': 'Soporte',
      'buyMeACoffee': 'Invítame un café',
      'data': 'Datos',
      'dataExport': 'Exportar datos',
      'dataImport': 'Importar datos',
      'preferences': 'Preferencias',
      'darkTheme': 'Modo oscuro',
      'notifications': 'Notificaciones',
      'taskReminders': 'Recordatorios de tareas',
      'separateSendButton': 'Botón de enviar separado',
      'swipeToDelete': 'Deslizar para eliminar',
      'compactCards': 'Tarjetas compactas',
      'amoledMode': 'Modo AMOLED',
      'dynamicColor': 'Color dinámico',
      'specialTheme': 'Tema especial',
      'skipWelcome': 'Saltar bienvenida',
      'deleteAllData': 'Eliminar todos los datos',
      'deleteAllDataSubtitle': 'Borrar permanentemente todas las notas y tareas',
      'language': 'Idioma',
      'system': 'Sistema',
      'english': 'English',
      'arabic': 'العربية',
      'notes': 'notas',
      'tasks': 'tareas',
      'chat': 'Chat',
      'typeAMessage': 'Escribe un mensaje...',
      'send': 'Enviar',
      'cancel': 'Cancelar',
      'confirm': 'Confirmar',
      'ok': 'OK',
      'home': 'Inicio',
      'noChatsYet': 'Aún no hay chats',
      'newChat': 'Nuevo chat',
      'dangerZone': 'Zona de peligro',
      'reportAnIssue': 'Reportar un problema',
      'delete': 'Eliminar',
      'allDataDeleted': 'Todos los datos eliminados.',
      'failedToExportData': 'Error al exportar datos',
      'importDataTitle': '¿Importar datos?',
      'importDataMessage': 'Esto agregará mensajes de un archivo exportado anteriormente a tu chat actual.',
      'importLabel': 'Importar',
      'dataImportedSuccessfully': 'Datos importados correctamente',
      'noExportFileFound': 'No se encontró archivo de exportación',
      'failedToImportData': 'Error al importar datos',
      'hexagonalButtonNextToBox': 'Botón hexagonal junto al cuadro',
      'buttonInsideComposeBox': 'Botón dentro del cuadro de composición',
      'swipeCardsToDelete': 'Desliza las tarjetas para eliminar',
      'longPressForActions': 'Mantén presionado para acciones',
      'hideIconsOnNoteTaskCards': 'Ocultar iconos en tarjetas de notas/tareas',
      'showIconsOnNoteTaskCards': 'Mostrar iconos en tarjetas de notas/tareas',
      'trueBlackBackground': 'Fondo negro verdadero',
      'useWallpaperColors': 'Usar colores del fondo de pantalla',
      'customColorScheme': 'Esquema de color personalizado',
      'goDirectlyToHomeOnLaunch': 'Ir directamente al inicio al abrir',
      'checkForUpdates': 'Buscar actualizaciones',
      'checkingForUpdates': 'Buscando actualizaciones...',
      'failedToCheckForUpdates': 'Error al buscar actualizaciones',
      'download': 'Descargar',
      'youAreUsingLatestVersion': 'Estás usando la última versión',
      'joinTelegramGroup': 'Unirse al grupo de Telegram',
      'getSupportAndUpdates': 'Obtener soporte y actualizaciones',
      'supportTheDeveloper': 'Apoyar al desarrollador',
      'suggestAFeature': 'Sugerir una función',
      'deleteAllDataConfirmation': 'Esta acción no se puede deshacer. Todos tus pensamientos y tareas serán eliminados permanentemente.',
      'myOrdoData': 'Mis datos de Ordo',
      'updateAvailable': 'Actualizar',
      'from': 'de',
      'craftedBy': 'Creado por',
      'madeInLibya': 'Hecho en Libia',
      'softwareDeveloperBuildingOrdo': 'Desarrollador de software construyendo Ordo.',
      'gitHubProfile': 'Perfil de GitHub',
      'chats': 'Chats',
      'deleteChatTitle': '¿Eliminar chat?',
      'deleteChatMessage': 'Esto eliminará permanentemente este chat y todos sus mensajes.',
      'startNewConversationHint': 'Inicia una nueva conversación\ntocando el botón de abajo',
      'justNow': 'Ahora mismo',
      'minutesAgo': 'hace {minutes}m',
      'hoursAgo': 'hace {hours}h',
      'daysAgo': 'hace {days}d',
      'active': 'Activo',
      'deleteChatTooltip': 'Eliminar chat',
      'deleteThoughtTitle': '¿Eliminar pensamiento?',
      'deleteThoughtMessage': 'Esta acción no se puede deshacer.',
      'editThought': 'Editar pensamiento',
      'save': 'Guardar',
      'markIncomplete': 'Marcar como incompleto',
      'markComplete': 'Marcar como completo',
      'setReminder': 'Configurar recordatorio',
      'copyText': 'Copiar texto',
      'labelTask': 'TAREA',
      'labelNote': 'NOTA',
      'emptySpaceTitle': 'Tu espacio está vacío',
      'emptySpaceMessage': 'Escribe una nota o tarea abajo y presiona enviar para comenzar.',
      'typeThoughtHint': 'Escribe un pensamiento...',
      'addTaskHint': 'Añade una tarea...',
      'enterChatNameHint': 'Ingresa el nombre del chat...',
      'suggestions': 'Sugerencias',
      'createChat': 'Crear chat',
      'setReminderTitle': 'Configurar recordatorio',
      'setReminderMessage': 'Elige cuándo quieres que te recordemos esta tarea',
      'skip': 'Saltar',
      'setReminderButton': 'Configurar recordatorio',
      'suggestionMyThoughts': 'Mis pensamientos',
      'suggestionDailyTasks': 'Tareas diarias',
      'suggestionProjectIdeas': 'Ideas de proyectos',
      'suggestionPersonalNotes': 'Notas personales',
      'suggestionWorkJournal': 'Diario de trabajo',
    },
    'id': {
      'appName': 'ordo',
      'settings': 'Pengaturan',
      'support': 'Dukungan',
      'buyMeACoffee': 'Traktir Saya Kopi',
      'data': 'Data',
      'dataExport': 'Ekspor Data',
      'dataImport': 'Impor Data',
      'preferences': 'Preferensi',
      'darkTheme': 'Mode Gelap',
      'notifications': 'Notifikasi',
      'taskReminders': 'Pengingat Tugas',
      'separateSendButton': 'Tombol Kirim Terpisah',
      'swipeToDelete': 'Geser untuk Hapus',
      'compactCards': 'Kartu Ringkas',
      'amoledMode': 'Mode AMOLED',
      'dynamicColor': 'Warna Dinamis',
      'specialTheme': 'Tema Khusus',
      'skipWelcome': 'Lewati Sambutan',
      'deleteAllData': 'Hapus Semua Data',
      'deleteAllDataSubtitle': 'Hapus permanen semua catatan dan tugas',
      'language': 'Bahasa',
      'system': 'Sistem',
      'english': 'English',
      'arabic': 'العربية',
      'notes': 'catatan',
      'tasks': 'tugas',
      'chat': 'Obrolan',
      'typeAMessage': 'Ketik pesan...',
      'send': 'Kirim',
      'cancel': 'Batal',
      'confirm': 'Konfirmasi',
      'ok': 'OK',
      'home': 'Beranda',
      'noChatsYet': 'Belum ada obrolan',
      'newChat': 'Obrolan Baru',
      'dangerZone': 'Zona Berbahaya',
      'reportAnIssue': 'Laporkan Masalah',
      'delete': 'Hapus',
      'allDataDeleted': 'Semua data telah dihapus.',
      'failedToExportData': 'Gagal mengekspor data',
      'importDataTitle': 'Impor data?',
      'importDataMessage': 'Ini akan menambahkan pesan dari file ekspor sebelumnya ke obrolan Anda saat ini.',
      'importLabel': 'Impor',
      'dataImportedSuccessfully': 'Data berhasil diimpor',
      'noExportFileFound': 'File ekspor tidak ditemukan',
      'failedToImportData': 'Gagal mengimpor data',
      'hexagonalButtonNextToBox': 'Tombol heksagonal di samping kotak',
      'buttonInsideComposeBox': 'Tombol di dalam kotak tulis',
      'swipeCardsToDelete': 'Geser kartu untuk menghapus',
      'longPressForActions': 'Tekan lama untuk tindakan',
      'hideIconsOnNoteTaskCards': 'Sembunyikan ikon di kartu catatan/tugas',
      'showIconsOnNoteTaskCards': 'Tampilkan ikon di kartu catatan/tugas',
      'trueBlackBackground': 'Latar belakang hitam sejati',
      'useWallpaperColors': 'Gunakan warna wallpaper',
      'customColorScheme': 'Skema warna kustom',
      'goDirectlyToHomeOnLaunch': 'Langsung ke beranda saat dibuka',
      'checkForUpdates': 'Periksa Pembaruan',
      'checkingForUpdates': 'Memeriksa pembaruan...',
      'failedToCheckForUpdates': 'Gagal memeriksa pembaruan',
      'download': 'Unduh',
      'youAreUsingLatestVersion': 'Anda menggunakan versi terbaru',
      'joinTelegramGroup': 'Gabung Grup Telegram',
      'getSupportAndUpdates': 'Dapatkan dukungan dan pembaruan',
      'supportTheDeveloper': 'Dukung Pengembang',
      'suggestAFeature': 'Sarankan Fitur',
      'deleteAllDataConfirmation': 'Tindakan ini tidak dapat dibatalkan. Semua pemikiran dan tugas Anda akan dihapus secara permanen.',
      'myOrdoData': 'Data Ordo Saya',
      'updateAvailable': 'Pembaruan Tersedia',
      'from': 'dari',
      'craftedBy': 'Dibuat oleh',
      'madeInLibya': 'Dibuat di Libya',
      'softwareDeveloperBuildingOrdo': 'Pengembang perangkat lunak yang membangun Ordo.',
      'gitHubProfile': 'Profil GitHub',
      'chats': 'Obrolan',
      'deleteChatTitle': 'Hapus obrolan?',
      'deleteChatMessage': 'Ini akan menghapus obrolan ini dan semua pesannya secara permanen.',
      'startNewConversationHint': 'Mulai percakapan baru\ndengan menekan tombol di bawah',
      'justNow': 'Baru saja',
      'minutesAgo': '{minutes}m yang lalu',
      'hoursAgo': '{hours}j yang lalu',
      'daysAgo': '{days}h yang lalu',
      'active': 'Aktif',
      'deleteChatTooltip': 'Hapus obrolan',
      'deleteThoughtTitle': 'Hapus pemikiran?',
      'deleteThoughtMessage': 'Tindakan ini tidak dapat dibatalkan.',
      'editThought': 'Edit Pemikiran',
      'save': 'Simpan',
      'markIncomplete': 'Tandai Belum Selesai',
      'markComplete': 'Tandai Selesai',
      'setReminder': 'Atur Pengingat',
      'copyText': 'Salin Teks',
      'labelTask': 'TUGAS',
      'labelNote': 'CATATAN',
      'emptySpaceTitle': 'Ruang Anda kosong',
      'emptySpaceMessage': 'Tulis catatan atau tugas di bawah dan tekan kirim untuk memulai.',
      'typeThoughtHint': 'Tulis pemikiran...',
      'addTaskHint': 'Tambahkan tugas...',
      'enterChatNameHint': 'Masukkan nama obrolan...',
      'suggestions': 'Saran',
      'createChat': 'Buat Obrolan',
      'setReminderTitle': 'Atur Pengingat',
      'setReminderMessage': 'Pilih kapan Anda ingin diingatkan tentang tugas ini',
      'skip': 'Lewati',
      'setReminderButton': 'Atur Pengingat',
      'suggestionMyThoughts': 'Pemikiran Saya',
      'suggestionDailyTasks': 'Tugas Harian',
      'suggestionProjectIdeas': 'Ide Proyek',
      'suggestionPersonalNotes': 'Catatan Pribadi',
      'suggestionWorkJournal': 'Jurnal Kerja',
    },
    'vi': {
      'appName': 'ordo',
      'settings': 'Cài đặt',
      'support': 'Hỗ trợ',
      'buyMeACoffee': 'Mua cho tôi một ly cà phê',
      'data': 'Dữ liệu',
      'dataExport': 'Xuất dữ liệu',
      'dataImport': 'Nhập dữ liệu',
      'preferences': 'Tùy chọn',
      'darkTheme': 'Chế độ tối',
      'notifications': 'Thông báo',
      'taskReminders': 'Nhắc nhở nhiệm vụ',
      'separateSendButton': 'Nút gửi riêng',
      'swipeToDelete': 'Vuốt để xóa',
      'compactCards': 'Thẻ gọn nhẹ',
      'amoledMode': 'Chế độ AMOLED',
      'dynamicColor': 'Màu động',
      'specialTheme': 'Chủ đề đặc biệt',
      'skipWelcome': 'Bỏ qua chào mừng',
      'deleteAllData': 'Xóa tất cả dữ liệu',
      'deleteAllDataSubtitle': 'Xóa vĩnh viễn tất cả ghi chú và nhiệm vụ',
      'language': 'Ngôn ngữ',
      'system': 'Hệ thống',
      'english': 'English',
      'arabic': 'العربية',
      'notes': 'ghi chú',
      'tasks': 'nhiệm vụ',
      'chat': 'Trò chuyện',
      'typeAMessage': 'Nhập tin nhắn...',
      'send': 'Gửi',
      'cancel': 'Hủy',
      'confirm': 'Xác nhận',
      'ok': 'OK',
      'home': 'Trang chủ',
      'noChatsYet': 'Chưa có cuộc trò chuyện nào',
      'newChat': 'Trò chuyện mới',
      'dangerZone': 'Khu vực nguy hiểm',
      'reportAnIssue': 'Báo cáo sự cố',
      'delete': 'Xóa',
      'allDataDeleted': 'Tất cả dữ liệu đã được xóa.',
      'failedToExportData': 'Xuất dữ liệu thất bại',
      'importDataTitle': 'Nhập dữ liệu?',
      'importDataMessage': 'Thao tác này sẽ thêm tin nhắn từ tệp đã xuất trước đó vào cuộc trò chuyện hiện tại của bạn.',
      'importLabel': 'Nhập',
      'dataImportedSuccessfully': 'Dữ liệu đã được nhập thành công',
      'noExportFileFound': 'Không tìm thấy tệp xuất',
      'failedToImportData': 'Nhập dữ liệu thất bại',
      'hexagonalButtonNextToBox': 'Nút lục giác bên cạnh hộp',
      'buttonInsideComposeBox': 'Nút bên trong hộp soạn thảo',
      'swipeCardsToDelete': 'Vuốt thẻ để xóa',
      'longPressForActions': 'Nhấn giữ để xem thao tác',
      'hideIconsOnNoteTaskCards': 'Ẩn biểu tượng trên thẻ ghi chú/nhiệm vụ',
      'showIconsOnNoteTaskCards': 'Hiện biểu tượng trên thẻ ghi chú/nhiệm vụ',
      'trueBlackBackground': 'Nền đen thuần',
      'useWallpaperColors': 'Sử dụng màu hình nền',
      'customColorScheme': 'Bảng màu tùy chỉnh',
      'goDirectlyToHomeOnLaunch': 'Đi thẳng đến trang chủ khi mở',
      'checkForUpdates': 'Kiểm tra cập nhật',
      'checkingForUpdates': 'Đang kiểm tra cập nhật...',
      'failedToCheckForUpdates': 'Kiểm tra cập nhật thất bại',
      'download': 'Tải xuống',
      'youAreUsingLatestVersion': 'Bạn đang sử dụng phiên bản mới nhất',
      'joinTelegramGroup': 'Tham gia nhóm Telegram',
      'getSupportAndUpdates': 'Nhận hỗ trợ và cập nhật',
      'supportTheDeveloper': 'Ủng hộ nhà phát triển',
      'suggestAFeature': 'Đề xuất tính năng',
      'deleteAllDataConfirmation': 'Hành động này không thể hoàn tác. Tất cả suy nghĩ và nhiệm vụ của bạn sẽ bị xóa vĩnh viễn.',
      'myOrdoData': 'Dữ liệu Ordo của tôi',
      'updateAvailable': 'Có bản cập nhật',
      'from': 'từ',
      'craftedBy': 'Được tạo bởi',
      'madeInLibya': 'Được làm tại Libya',
      'softwareDeveloperBuildingOrdo': 'Nhà phát triển phần mềm xây dựng Ordo.',
      'gitHubProfile': 'Hồ sơ GitHub',
      'chats': 'Trò chuyện',
      'deleteChatTitle': 'Xóa trò chuyện?',
      'deleteChatMessage': 'Thao tác này sẽ xóa vĩnh viễn cuộc trò chuyện này và tất cả tin nhắn.',
      'startNewConversationHint': 'Bắt đầu cuộc trò chuyện mới\nbằng cách nhấn nút bên dưới',
      'justNow': 'Vừa xong',
      'minutesAgo': '{minutes} phút trước',
      'hoursAgo': '{hours} giờ trước',
      'daysAgo': '{days} ngày trước',
      'active': 'Hoạt động',
      'deleteChatTooltip': 'Xóa trò chuyện',
      'deleteThoughtTitle': 'Xóa suy nghĩ?',
      'deleteThoughtMessage': 'Hành động này không thể hoàn tác.',
      'editThought': 'Chỉnh sửa suy nghĩ',
      'save': 'Lưu',
      'markIncomplete': 'Đánh dấu chưa hoàn thành',
      'markComplete': 'Đánh dấu hoàn thành',
      'setReminder': 'Đặt lời nhắc',
      'copyText': 'Sao chép văn bản',
      'labelTask': 'NHIỆM VỤ',
      'labelNote': 'GHI CHÚ',
      'emptySpaceTitle': 'Không gian của bạn trống',
      'emptySpaceMessage': 'Viết ghi chú hoặc nhiệm vụ bên dưới và nhấn gửi để bắt đầu.',
      'typeThoughtHint': 'Viết suy nghĩ...',
      'addTaskHint': 'Thêm nhiệm vụ...',
      'enterChatNameHint': 'Nhập tên trò chuyện...',
      'suggestions': 'Gợi ý',
      'createChat': 'Tạo trò chuyện',
      'setReminderTitle': 'Đặt lời nhắc',
      'setReminderMessage': 'Chọn thời gian bạn muốn được nhắc về nhiệm vụ này',
      'skip': 'Bỏ qua',
      'setReminderButton': 'Đặt lời nhắc',
      'suggestionMyThoughts': 'Suy nghĩ của tôi',
      'suggestionDailyTasks': 'Nhiệm vụ hàng ngày',
      'suggestionProjectIdeas': 'Ý tưởng dự án',
      'suggestionPersonalNotes': 'Ghi chú cá nhân',
      'suggestionWorkJournal': 'Nhật ký công việc',
    },
    'zh': {
      'appName': 'ordo',
      'settings': '设置',
      'support': '支持',
      'buyMeACoffee': '请我喝杯咖啡',
      'data': '数据',
      'dataExport': '导出数据',
      'dataImport': '导入数据',
      'preferences': '偏好设置',
      'darkTheme': '深色模式',
      'notifications': '通知',
      'taskReminders': '任务提醒',
      'separateSendButton': '独立发送按钮',
      'swipeToDelete': '滑动删除',
      'compactCards': '紧凑卡片',
      'amoledMode': 'AMOLED模式',
      'dynamicColor': '动态颜色',
      'specialTheme': '特殊主题',
      'skipWelcome': '跳过欢迎',
      'deleteAllData': '删除所有数据',
      'deleteAllDataSubtitle': '永久删除所有笔记和任务',
      'language': '语言',
      'system': '系统',
      'english': 'English',
      'arabic': 'العربية',
      'notes': '笔记',
      'tasks': '任务',
      'chat': '聊天',
      'typeAMessage': '输入消息...',
      'send': '发送',
      'cancel': '取消',
      'confirm': '确认',
      'ok': '确定',
      'home': '首页',
      'noChatsYet': '暂无聊天',
      'newChat': '新建聊天',
      'dangerZone': '危险区域',
      'reportAnIssue': '报告问题',
      'delete': '删除',
      'allDataDeleted': '所有数据已删除。',
      'failedToExportData': '导出数据失败',
      'importDataTitle': '导入数据？',
      'importDataMessage': '这将从之前导出的文件向当前聊天添加消息。',
      'importLabel': '导入',
      'dataImportedSuccessfully': '数据导入成功',
      'noExportFileFound': '未找到导出文件',
      'failedToImportData': '导入数据失败',
      'hexagonalButtonNextToBox': '框旁的六角按钮',
      'buttonInsideComposeBox': '撰写框内的按钮',
      'swipeCardsToDelete': '滑动卡片删除',
      'longPressForActions': '长按进行操作',
      'hideIconsOnNoteTaskCards': '在笔记/任务卡片上隐藏图标',
      'showIconsOnNoteTaskCards': '在笔记/任务卡片上显示图标',
      'trueBlackBackground': '纯黑背景',
      'useWallpaperColors': '使用壁纸颜色',
      'customColorScheme': '自定义配色方案',
      'goDirectlyToHomeOnLaunch': '启动时直接进入主页',
      'checkForUpdates': '检查更新',
      'checkingForUpdates': '正在检查更新...',
      'failedToCheckForUpdates': '检查更新失败',
      'download': '下载',
      'youAreUsingLatestVersion': '您正在使用最新版本',
      'joinTelegramGroup': '加入Telegram群组',
      'getSupportAndUpdates': '获取支持和更新',
      'supportTheDeveloper': '支持开发者',
      'suggestAFeature': '建议功能',
      'deleteAllDataConfirmation': '此操作无法撤消。您的所有想法和任务将被永久删除。',
      'myOrdoData': '我的Ordo数据',
      'updateAvailable': '有可用更新',
      'from': '来自',
      'craftedBy': '由...制作',
      'madeInLibya': '利比亚制造',
      'softwareDeveloperBuildingOrdo': '正在构建Ordo的软件开发者。',
      'gitHubProfile': 'GitHub个人资料',
      'chats': '聊天',
      'deleteChatTitle': '删除聊天？',
      'deleteChatMessage': '这将永久删除此聊天及其所有消息。',
      'startNewConversationHint': '点击下方按钮\n开始新对话',
      'justNow': '刚刚',
      'minutesAgo': '{minutes}分钟前',
      'hoursAgo': '{hours}小时前',
      'daysAgo': '{days}天前',
      'active': '活跃',
      'deleteChatTooltip': '删除聊天',
      'deleteThoughtTitle': '删除想法？',
      'deleteThoughtMessage': '此操作无法撤消。',
      'editThought': '编辑想法',
      'save': '保存',
      'markIncomplete': '标记为未完成',
      'markComplete': '标记为完成',
      'setReminder': '设置提醒',
      'copyText': '复制文本',
      'labelTask': '任务',
      'labelNote': '笔记',
      'emptySpaceTitle': '您的空间是空的',
      'emptySpaceMessage': '在下方写下笔记或任务，然后点击发送开始。',
      'typeThoughtHint': '写下想法...',
      'addTaskHint': '添加任务...',
      'enterChatNameHint': '输入聊天名称...',
      'suggestions': '建议',
      'createChat': '创建聊天',
      'setReminderTitle': '设置提醒',
      'setReminderMessage': '选择您希望被提醒此任务的时间',
      'skip': '跳过',
      'setReminderButton': '设置提醒',
      'suggestionMyThoughts': '我的想法',
      'suggestionDailyTasks': '日常任务',
      'suggestionProjectIdeas': '项目创意',
      'suggestionPersonalNotes': '个人笔记',
      'suggestionWorkJournal': '工作日志',
    },
    'es-MX': {
      'appName': 'ordo',
      'settings': 'Configuración',
      'support': 'Soporte',
      'buyMeACoffee': 'Invítame un café',
      'data': 'Datos',
      'dataExport': 'Exportar datos',
      'dataImport': 'Importar datos',
      'preferences': 'Preferencias',
      'darkTheme': 'Modo oscuro',
      'notifications': 'Notificaciones',
      'taskReminders': 'Recordatorios de tareas',
      'separateSendButton': 'Botón de enviar separado',
      'swipeToDelete': 'Deslizar para eliminar',
      'compactCards': 'Tarjetas compactas',
      'amoledMode': 'Modo AMOLED',
      'dynamicColor': 'Color dinámico',
      'specialTheme': 'Tema especial',
      'skipWelcome': 'Saltar bienvenida',
      'deleteAllData': 'Eliminar todos los datos',
      'deleteAllDataSubtitle': 'Borrar permanentemente todas las notas y tareas',
      'language': 'Idioma',
      'system': 'Sistema',
      'english': 'English',
      'arabic': 'العربية',
      'notes': 'notas',
      'tasks': 'tareas',
      'chat': 'Chat',
      'typeAMessage': 'Escribe un mensaje...',
      'send': 'Enviar',
      'cancel': 'Cancelar',
      'confirm': 'Confirmar',
      'ok': 'OK',
      'home': 'Inicio',
      'noChatsYet': 'Aún no hay chats',
      'newChat': 'Nuevo chat',
      'dangerZone': 'Zona de peligro',
      'reportAnIssue': 'Reportar un problema',
      'delete': 'Eliminar',
      'allDataDeleted': 'Todos los datos eliminados.',
      'failedToExportData': 'Error al exportar datos',
      'importDataTitle': '¿Importar datos?',
      'importDataMessage': 'Esto agregará mensajes de un archivo exportado anteriormente a tu chat actual.',
      'importLabel': 'Importar',
      'dataImportedSuccessfully': 'Datos importados correctamente',
      'noExportFileFound': 'No se encontró archivo de exportación',
      'failedToImportData': 'Error al importar datos',
      'hexagonalButtonNextToBox': 'Botón hexagonal junto al cuadro',
      'buttonInsideComposeBox': 'Botón dentro del cuadro de composición',
      'swipeCardsToDelete': 'Desliza las tarjetas para eliminar',
      'longPressForActions': 'Mantén presionado para acciones',
      'hideIconsOnNoteTaskCards': 'Ocultar iconos en tarjetas de notas/tareas',
      'showIconsOnNoteTaskCards': 'Mostrar iconos en tarjetas de notas/tareas',
      'trueBlackBackground': 'Fondo negro verdadero',
      'useWallpaperColors': 'Usar colores del fondo de pantalla',
      'customColorScheme': 'Esquema de color personalizado',
      'goDirectlyToHomeOnLaunch': 'Ir directamente al inicio al abrir',
      'checkForUpdates': 'Buscar actualizaciones',
      'checkingForUpdates': 'Buscando actualizaciones...',
      'failedToCheckForUpdates': 'Error al buscar actualizaciones',
      'download': 'Descargar',
      'youAreUsingLatestVersion': 'Estás usando la última versión',
      'joinTelegramGroup': 'Unirse al grupo de Telegram',
      'getSupportAndUpdates': 'Obtener soporte y actualizaciones',
      'supportTheDeveloper': 'Apoyar al desarrollador',
      'suggestAFeature': 'Sugerir una función',
      'deleteAllDataConfirmation': 'Esta acción no se puede deshacer. Todos tus pensamientos y tareas serán eliminados permanentemente.',
      'myOrdoData': 'Mis datos de Ordo',
      'updateAvailable': 'Actualizar',
      'from': 'de',
      'craftedBy': 'Creado por',
      'madeInLibya': 'Hecho en Libia',
      'softwareDeveloperBuildingOrdo': 'Desarrollador de software construyendo Ordo.',
      'gitHubProfile': 'Perfil de GitHub',
      'chats': 'Chats',
      'deleteChatTitle': '¿Eliminar chat?',
      'deleteChatMessage': 'Esto eliminará permanentemente este chat y todos sus mensajes.',
      'startNewConversationHint': 'Inicia una nueva conversación\ntocando el botón de abajo',
      'justNow': 'Ahora mismo',
      'minutesAgo': 'hace {minutes}m',
      'hoursAgo': 'hace {hours}h',
      'daysAgo': 'hace {days}d',
      'active': 'Activo',
      'deleteChatTooltip': 'Eliminar chat',
      'deleteThoughtTitle': '¿Eliminar pensamiento?',
      'deleteThoughtMessage': 'Esta acción no se puede deshacer.',
      'editThought': 'Editar pensamiento',
      'save': 'Guardar',
      'markIncomplete': 'Marcar como incompleto',
      'markComplete': 'Marcar como completo',
      'setReminder': 'Configurar recordatorio',
      'copyText': 'Copiar texto',
      'labelTask': 'TAREA',
      'labelNote': 'NOTA',
      'emptySpaceTitle': 'Tu espacio está vacío',
      'emptySpaceMessage': 'Escribe una nota o tarea abajo y presiona enviar para comenzar.',
      'typeThoughtHint': 'Escribe un pensamiento...',
      'addTaskHint': 'Añade una tarea...',
      'enterChatNameHint': 'Ingresa el nombre del chat...',
      'suggestions': 'Sugerencias',
      'createChat': 'Crear chat',
      'setReminderTitle': 'Configurar recordatorio',
      'setReminderMessage': 'Elige cuándo quieres que te recordemos esta tarea',
      'skip': 'Saltar',
      'setReminderButton': 'Configurar recordatorio',
      'suggestionMyThoughts': 'Mis pensamientos',
      'suggestionDailyTasks': 'Tareas diarias',
      'suggestionProjectIdeas': 'Ideas de proyectos',
      'suggestionPersonalNotes': 'Notas personales',
      'suggestionWorkJournal': 'Diario de trabajo',
    },
    'pt-BR': {
      'appName': 'ordo',
      'settings': 'Configurações',
      'support': 'Suporte',
      'buyMeACoffee': 'Me pague um café',
      'data': 'Dados',
      'dataExport': 'Exportar dados',
      'dataImport': 'Importar dados',
      'preferences': 'Preferências',
      'darkTheme': 'Modo escuro',
      'notifications': 'Notificações',
      'taskReminders': 'Lembretes de tarefas',
      'separateSendButton': 'Botão de envio separado',
      'swipeToDelete': 'Deslizar para excluir',
      'compactCards': 'Cartões compactos',
      'amoledMode': 'Modo AMOLED',
      'dynamicColor': 'Cor dinâmica',
      'specialTheme': 'Tema especial',
      'skipWelcome': 'Pular boas-vindas',
      'deleteAllData': 'Excluir todos os dados',
      'deleteAllDataSubtitle': 'Apagar permanentemente todas as notas e tarefas',
      'language': 'Idioma',
      'system': 'Sistema',
      'english': 'English',
      'arabic': 'العربية',
      'notes': 'notas',
      'tasks': 'tarefas',
      'chat': 'Chat',
      'typeAMessage': 'Digite uma mensagem...',
      'send': 'Enviar',
      'cancel': 'Cancelar',
      'confirm': 'Confirmar',
      'ok': 'OK',
      'home': 'Início',
      'noChatsYet': 'Ainda não há chats',
      'newChat': 'Novo chat',
      'dangerZone': 'Zona de perigo',
      'reportAnIssue': 'Relatar um problema',
      'delete': 'Excluir',
      'allDataDeleted': 'Todos os dados foram excluídos.',
      'failedToExportData': 'Falha ao exportar dados',
      'importDataTitle': 'Importar dados?',
      'importDataMessage': 'Isso adicionará mensagens de um arquivo exportado anteriormente ao seu chat atual.',
      'importLabel': 'Importar',
      'dataImportedSuccessfully': 'Dados importados com sucesso',
      'noExportFileFound': 'Nenhum arquivo de exportação encontrado',
      'failedToImportData': 'Falha ao importar dados',
      'hexagonalButtonNextToBox': 'Botão hexagonal ao lado da caixa',
      'buttonInsideComposeBox': 'Botão dentro da caixa de composição',
      'swipeCardsToDelete': 'Deslize os cartões para excluir',
      'longPressForActions': 'Pressione e segure para ações',
      'hideIconsOnNoteTaskCards': 'Ocultar ícones nos cartões de notas/tarefas',
      'showIconsOnNoteTaskCards': 'Mostrar ícones nos cartões de notas/tarefas',
      'trueBlackBackground': 'Fundo preto verdadeiro',
      'useWallpaperColors': 'Usar cores do papel de parede',
      'customColorScheme': 'Esquema de cores personalizado',
      'goDirectlyToHomeOnLaunch': 'Ir diretamente para o início ao abrir',
      'checkForUpdates': 'Verificar atualizações',
      'checkingForUpdates': 'Verificando atualizações...',
      'failedToCheckForUpdates': 'Falha ao verificar atualizações',
      'download': 'Baixar',
      'youAreUsingLatestVersion': 'Você está usando a versão mais recente',
      'joinTelegramGroup': 'Entrar no grupo do Telegram',
      'getSupportAndUpdates': 'Obter suporte e atualizações',
      'supportTheDeveloper': 'Apoiar o desenvolvedor',
      'suggestAFeature': 'Sugerir um recurso',
      'deleteAllDataConfirmation': 'Esta ação não pode ser desfeita. Todos os seus pensamentos e tarefas serão permanentemente excluídos.',
      'myOrdoData': 'Meus dados do Ordo',
      'updateAvailable': 'Atualização disponível',
      'from': 'de',
      'craftedBy': 'Criado por',
      'madeInLibya': 'Feito na Líbia',
      'softwareDeveloperBuildingOrdo': 'Desenvolvedor de software construindo o Ordo.',
      'gitHubProfile': 'Perfil do GitHub',
      'chats': 'Chats',
      'deleteChatTitle': 'Excluir chat?',
      'deleteChatMessage': 'Isso excluirá permanentemente este chat e todas as suas mensagens.',
      'startNewConversationHint': 'Inicie uma nova conversa\ntocando no botão abaixo',
      'justNow': 'Agora mesmo',
      'minutesAgo': 'há {minutes}min',
      'hoursAgo': 'há {hours}h',
      'daysAgo': 'há {days}d',
      'active': 'Ativo',
      'deleteChatTooltip': 'Excluir chat',
      'deleteThoughtTitle': 'Excluir pensamento?',
      'deleteThoughtMessage': 'Esta ação não pode ser desfeita.',
      'editThought': 'Editar pensamento',
      'save': 'Salvar',
      'markIncomplete': 'Marcar como incompleto',
      'markComplete': 'Marcar como completo',
      'setReminder': 'Definir lembrete',
      'copyText': 'Copiar texto',
      'labelTask': 'TAREFA',
      'labelNote': 'NOTA',
      'emptySpaceTitle': 'Seu espaço está vazio',
      'emptySpaceMessage': 'Escreva uma nota ou tarefa abaixo e pressione enviar para começar.',
      'typeThoughtHint': 'Escreva um pensamento...',
      'addTaskHint': 'Adicione uma tarefa...',
      'enterChatNameHint': 'Insira o nome do chat...',
      'suggestions': 'Sugestões',
      'createChat': 'Criar chat',
      'setReminderTitle': 'Definir lembrete',
      'setReminderMessage': 'Escolha quando você deseja ser lembrado sobre esta tarefa',
      'skip': 'Pular',
      'setReminderButton': 'Definir lembrete',
      'suggestionMyThoughts': 'Meus pensamentos',
      'suggestionDailyTasks': 'Tarefas diárias',
      'suggestionProjectIdeas': 'Ideias de projetos',
      'suggestionPersonalNotes': 'Notas pessoais',
      'suggestionWorkJournal': 'Diário de trabalho',
    },
    'fil': {
      'appName': 'ordo',
      'settings': 'Mga Setting',
      'support': 'Suporta',
      'buyMeACoffee': 'Bilhan mo ako ng kape',
      'data': 'Data',
      'dataExport': 'I-export ang data',
      'dataImport': 'I-import ang data',
      'preferences': 'Mga Kagustuhan',
      'darkTheme': 'Madilim na mode',
      'notifications': 'Mga Notipikasyon',
      'taskReminders': 'Mga Paalala ng Gawain',
      'separateSendButton': 'Hiwalay na pindutan ng pagpapadala',
      'swipeToDelete': 'Mag-swipe para burahin',
      'compactCards': 'Mga siksik na kard',
      'amoledMode': 'AMOLED mode',
      'dynamicColor': 'Dinamikong kulay',
      'specialTheme': 'Espesyal na tema',
      'skipWelcome': 'Laktawan ang pagbati',
      'deleteAllData': 'Burahin lahat ng data',
      'deleteAllDataSubtitle': 'Permanenteng burahin lahat ng tala at gawain',
      'language': 'Wika',
      'system': 'System',
      'english': 'English',
      'arabic': 'العربية',
      'notes': 'mga tala',
      'tasks': 'mga gawain',
      'chat': 'Chat',
      'typeAMessage': 'Mag-type ng mensahe...',
      'send': 'Ipadala',
      'cancel': 'Kanselahin',
      'confirm': 'Kumpirmahin',
      'ok': 'OK',
      'home': 'Bahay',
      'noChatsYet': 'Wala pang chat',
      'newChat': 'Bagong chat',
      'dangerZone': 'Mapanganib na sona',
      'reportAnIssue': 'Mag-ulat ng isyu',
      'delete': 'Burahin',
      'allDataDeleted': 'Lahat ng data ay nabura na.',
      'failedToExportData': 'Nabigo ang pag-export ng data',
      'importDataTitle': 'I-import ang data?',
      'importDataMessage': 'Magdaragdag ito ng mga mensahe mula sa dating na-export na file sa iyong kasalukuyang chat.',
      'importLabel': 'I-import',
      'dataImportedSuccessfully': 'Matagumpay na na-import ang data',
      'noExportFileFound': 'Walang nakitang export file',
      'failedToImportData': 'Nabigo ang pag-import ng data',
      'hexagonalButtonNextToBox': 'Heksagonal na pindutan sa tabi ng kahon',
      'buttonInsideComposeBox': 'Pindutan sa loob ng kahon ng pagsulat',
      'swipeCardsToDelete': 'Mag-swipe ng mga kard para burahin',
      'longPressForActions': 'Pindutin nang matagal para sa mga aksyon',
      'hideIconsOnNoteTaskCards': 'Itago ang mga icon sa kard ng tala/gawain',
      'showIconsOnNoteTaskCards': 'Ipakita ang mga icon sa kard ng tala/gawain',
      'trueBlackBackground': 'Tunay na itim na background',
      'useWallpaperColors': 'Gamitin ang mga kulay ng wallpaper',
      'customColorScheme': 'Pasadyang scheme ng kulay',
      'goDirectlyToHomeOnLaunch': 'Diretso sa bahay kapag binuksan',
      'checkForUpdates': 'Suriin ang mga update',
      'checkingForUpdates': 'Sinusuri ang mga update...',
      'failedToCheckForUpdates': 'Nabigo ang pagsuri ng mga update',
      'download': 'I-download',
      'youAreUsingLatestVersion': 'Ginagamit mo ang pinakabagong bersyon',
      'joinTelegramGroup': 'Sumali sa Telegram group',
      'getSupportAndUpdates': 'Kumuha ng suporta at mga update',
      'supportTheDeveloper': 'Suportahan ang developer',
      'suggestAFeature': 'Magmungkahi ng tampok',
      'deleteAllDataConfirmation': 'Ang aksyong ito ay hindi na maaaring balikan. Lahat ng iyong mga iniisip at gawain ay permanenteng tatanggalin.',
      'myOrdoData': 'Aking data ng Ordo',
      'updateAvailable': 'May available na update',
      'from': 'mula sa',
      'craftedBy': 'Ginawa ni',
      'madeInLibya': 'Ginawa sa Libya',
      'softwareDeveloperBuildingOrdo': 'Software developer na gumagawa ng Ordo.',
      'gitHubProfile': 'Profile sa GitHub',
      'chats': 'Mga Chat',
      'deleteChatTitle': 'Burahin ang chat?',
      'deleteChatMessage': 'Permanenteng buburahin nito ang chat na ito at lahat ng mga mensahe nito.',
      'startNewConversationHint': 'Magsimula ng bagong pag-uusap\nsa pamamagitan ng pagpindot sa pindutan sa ibaba',
      'justNow': 'Katatapos lang',
      'minutesAgo': '{minutes} minuto ang nakalipas',
      'hoursAgo': '{hours} oras ang nakalipas',
      'daysAgo': '{days} araw ang nakalipas',
      'active': 'Aktibo',
      'deleteChatTooltip': 'Burahin ang chat',
      'deleteThoughtTitle': 'Burahin ang iniisip?',
      'deleteThoughtMessage': 'Ang aksyong ito ay hindi na maaaring balikan.',
      'editThought': 'I-edit ang iniisip',
      'save': 'I-save',
      'markIncomplete': 'Markahan bilang hindi kumpleto',
      'markComplete': 'Markahan bilang kumpleto',
      'setReminder': 'Magtakda ng paalala',
      'copyText': 'Kopyahin ang teksto',
      'labelTask': 'GAWAIN',
      'labelNote': 'TALA',
      'emptySpaceTitle': 'Walang laman ang iyong espasyo',
      'emptySpaceMessage': 'Sumulat ng tala o gawain sa ibaba at pindutin ang ipadala para magsimula.',
      'typeThoughtHint': 'Sumulat ng iniisip...',
      'addTaskHint': 'Magdagdag ng gawain...',
      'enterChatNameHint': 'Ilagay ang pangalan ng chat...',
      'suggestions': 'Mga Mungkahi',
      'createChat': 'Gumawa ng chat',
      'setReminderTitle': 'Magtakda ng paalala',
      'setReminderMessage': 'Pumili kung kailan mo gustong paalalahanan tungkol sa gawaing ito',
      'skip': 'Laktawan',
      'setReminderButton': 'Magtakda ng paalala',
      'suggestionMyThoughts': 'Aking mga iniisip',
      'suggestionDailyTasks': 'Araw-araw na gawain',
      'suggestionProjectIdeas': 'Mga ideya sa proyekto',
      'suggestionPersonalNotes': 'Personal na mga tala',
      'suggestionWorkJournal': 'Talaan ng trabaho',
    },
    'ur': {
      'appName': 'ordo',
      'settings': 'ترتیبات',
      'support': 'معاونت',
      'buyMeACoffee': 'میرے لیے کافی خریدیں',
      'data': 'ڈیٹا',
      'dataExport': 'ڈیٹا برآمد کریں',
      'dataImport': 'ڈیٹا درآمد کریں',
      'preferences': 'ترجیحات',
      'darkTheme': 'ڈارک موڈ',
      'notifications': 'اطلاعات',
      'taskReminders': 'کاموں کی یاد دہانی',
      'separateSendButton': 'الگ بھیجنے کا بٹن',
      'swipeToDelete': 'حذف کرنے کے لیے سوائپ کریں',
      'compactCards': 'کمپیکٹ کارڈز',
      'amoledMode': 'AMOLED موڈ',
      'dynamicColor': 'متحرک رنگ',
      'specialTheme': 'خصوصی تھیم',
      'skipWelcome': 'خوش آمدید چھوڑیں',
      'deleteAllData': 'تمام ڈیٹا حذف کریں',
      'deleteAllDataSubtitle': 'تمام نوٹس اور کاموں کو مستقل طور پر حذف کریں',
      'language': 'زبان',
      'system': 'سسٹم',
      'english': 'English',
      'arabic': 'العربية',
      'notes': 'نوٹس',
      'tasks': 'کام',
      'chat': 'چیٹ',
      'typeAMessage': 'پیغام لکھیں...',
      'send': 'بھیجیں',
      'cancel': 'منسوخ کریں',
      'confirm': 'تصدیق کریں',
      'ok': 'ٹھیک ہے',
      'home': 'ہوم',
      'noChatsYet': 'ابھی تک کوئی چیٹ نہیں',
      'newChat': 'نئی چیٹ',
      'dangerZone': 'خطرناک زون',
      'reportAnIssue': 'مسئلہ رپورٹ کریں',
      'delete': 'حذف کریں',
      'allDataDeleted': 'تمام ڈیٹا حذف ہو گیا۔',
      'failedToExportData': 'ڈیٹا برآمد کرنے میں ناکام',
      'importDataTitle': 'ڈیٹا درآمد کریں؟',
      'importDataMessage': 'یہ پہلے برآمد کردہ فائل سے آپ کی موجودہ چیٹ میں پیغامات شامل کرے گا۔',
      'importLabel': 'درآمد کریں',
      'dataImportedSuccessfully': 'ڈیٹا کامیابی سے درآمد ہو گیا',
      'noExportFileFound': 'برآمد کردہ فائل نہیں ملی',
      'failedToImportData': 'ڈیٹا درآمد کرنے میں ناکام',
      'hexagonalButtonNextToBox': 'باکس کے ساتھ ہیکساگونل بٹن',
      'buttonInsideComposeBox': 'تحریری باکس کے اندر بٹن',
      'swipeCardsToDelete': 'کارڈز کو حذف کرنے کے لیے سوائپ کریں',
      'longPressForActions': 'عمل کے لیے دیر تک دبائیں',
      'hideIconsOnNoteTaskCards': 'نوٹ/ٹاسک کارڈز پر آئیکن چھپائیں',
      'showIconsOnNoteTaskCards': 'نوٹ/ٹاسک کارڈز پر آئیکن دکھائیں',
      'trueBlackBackground': 'حقیقی سیاہ پس منظر',
      'useWallpaperColors': 'وال پیپر کے رنگ استعمال کریں',
      'customColorScheme': 'اپنی مرضی کے رنگ سکیم',
      'goDirectlyToHomeOnLaunch': 'کھولتے ہی براہ راست ہوم پر جائیں',
      'checkForUpdates': 'اپ ڈیٹس چیک کریں',
      'checkingForUpdates': 'اپ ڈیٹس چیک ہو رہی ہیں...',
      'failedToCheckForUpdates': 'اپ ڈیٹس چیک کرنے میں ناکام',
      'download': 'ڈاؤن لوڈ کریں',
      'youAreUsingLatestVersion': 'آپ تازہ ترین ورژن استعمال کر رہے ہیں',
      'joinTelegramGroup': 'ٹیلیگرام گروپ میں شامل ہوں',
      'getSupportAndUpdates': 'معاونت اور اپ ڈیٹس حاصل کریں',
      'supportTheDeveloper': 'ڈویلپر کی حمایت کریں',
      'suggestAFeature': 'فیچر تجویز کریں',
      'deleteAllDataConfirmation': 'یہ عمل واپس نہیں لیا جا سکتا۔ آپ کے تمام خیالات اور کام مستقل طور پر حذف ہو جائیں گے۔',
      'myOrdoData': 'میرا Ordo ڈیٹا',
      'updateAvailable': 'اپ ڈیٹ دستیاب ہے',
      'from': 'سے',
      'craftedBy': 'تیار کردہ',
      'madeInLibya': 'لیبیا میں تیار کردہ',
      'softwareDeveloperBuildingOrdo': 'سافٹ ویئر ڈویلپر Ordo بنا رہا ہے۔',
      'gitHubProfile': 'GitHub پروفائل',
      'chats': 'چیٹس',
      'deleteChatTitle': 'چیٹ حذف کریں؟',
      'deleteChatMessage': 'یہ اس چیٹ اور اس کے تمام پیغامات کو مستقل طور پر حذف کر دے گا۔',
      'startNewConversationHint': 'نیچے دیے گئے بٹن کو دبا کر\nنئی گفتگو شروع کریں',
      'justNow': 'ابھی',
      'minutesAgo': '{minutes} منٹ پہلے',
      'hoursAgo': '{hours} گھنٹے پہلے',
      'daysAgo': '{days} دن پہلے',
      'active': 'فعال',
      'deleteChatTooltip': 'چیٹ حذف کریں',
      'deleteThoughtTitle': 'خیال حذف کریں؟',
      'deleteThoughtMessage': 'یہ عمل واپس نہیں لیا جا سکتا۔',
      'editThought': 'خیال میں ترمیم کریں',
      'save': 'محفوظ کریں',
      'markIncomplete': 'نامکمل نشان زد کریں',
      'markComplete': 'مکمل نشان زد کریں',
      'setReminder': 'یاد دہانی مقرر کریں',
      'copyText': 'متن کاپی کریں',
      'labelTask': 'کام',
      'labelNote': 'نوٹ',
      'emptySpaceTitle': 'آپ کی جگہ خالی ہے',
      'emptySpaceMessage': 'نیچے ایک نوٹ یا کام لکھیں اور شروع کرنے کے لیے بھیجیں دبائیں۔',
      'typeThoughtHint': 'ایک خیال لکھیں...',
      'addTaskHint': 'ایک کام شامل کریں...',
      'enterChatNameHint': 'چیٹ کا نام درج کریں...',
      'suggestions': 'تجاویز',
      'createChat': 'چیٹ بنائیں',
      'setReminderTitle': 'یاد دہانی مقرر کریں',
      'setReminderMessage': 'وہ وقت منتخب کریں جب آپ کو اس کام کی یاد دلائی جائے',
      'skip': 'چھوڑیں',
      'setReminderButton': 'یاد دہانی مقرر کریں',
      'suggestionMyThoughts': 'میرے خیالات',
      'suggestionDailyTasks': 'روزانہ کے کام',
      'suggestionProjectIdeas': 'پروجیکٹ کے آئیڈیاز',
      'suggestionPersonalNotes': 'ذاتی نوٹس',
      'suggestionWorkJournal': 'کام کی ڈائری',
    },
    'si': {
      'appName': 'ordo',
      'settings': 'සැකසුම්',
      'support': 'සහාය',
      'buyMeACoffee': 'මට කෝපි එකක් ගන්න',
      'data': 'දත්ත',
      'dataExport': 'දත්ත අපනයනය',
      'dataImport': 'දත්ත ආනයනය',
      'preferences': 'මනාප',
      'darkTheme': 'අඳුරු ප්‍රකාරය',
      'notifications': 'දැනුම්දීම්',
      'taskReminders': 'කාර්ය මතක් කිරීම්',
      'separateSendButton': 'වෙන separ යැවීම් බොත්තම',
      'swipeToDelete': 'මකා දැමීමට ස්වයිප් කරන්න',
      'compactCards': 'සංයුක්ත කාඩ්පත්',
      'amoledMode': 'AMOLED ප්‍රකාරය',
      'dynamicColor': 'ගතික වර්ණය',
      'specialTheme': 'විශේෂ තේමාව',
      'skipWelcome': 'පිළිගැනීම මඟ හරින්න',
      'deleteAllData': 'සියලු දත්ත මකන්න',
      'deleteAllDataSubtitle': 'සියලු සටහන් සහ කාර්ය ස්ථිරව මකන්න',
      'language': 'භාෂාව',
      'system': 'පද්ධතිය',
      'english': 'English',
      'arabic': 'العربية',
      'notes': 'සටහන්',
      'tasks': 'කාර්ය',
      'chat': 'කතාබස්',
      'typeAMessage': 'පණිවිඩයක් ලියන්න...',
      'send': 'යවන්න',
      'cancel': 'අවලංගු කරන්න',
      'confirm': 'තහවුරු කරන්න',
      'ok': 'හරි',
      'home': 'මුල් පිටුව',
      'noChatsYet': 'තවම කතාබස් නැත',
      'newChat': 'නව කතාබස්',
      'dangerZone': 'අනතුරු කලාපය',
      'reportAnIssue': 'ගැටලුවක් වාර්තා කරන්න',
      'delete': 'මකන්න',
      'allDataDeleted': 'සියලු දත්ත මකා දමන ලදී.',
      'failedToExportData': 'දත්ත අපනයනය අසාර්ථක විය',
      'importDataTitle': 'දත්ත ආනයනය කරන්න?',
      'importDataMessage': 'මෙය පෙර අපනයනය කළ ගොනුවකින් ඔබේ වත්මන් කතාබසට පණිවිඩ එක් කරයි.',
      'importLabel': 'ආනයනය',
      'dataImportedSuccessfully': 'දත්ත සාර්ථකව ආනයනය විය',
      'noExportFileFound': 'අපනයන ගොනුව හමු නොවීය',
      'failedToImportData': 'දත්ත ආනයනය අසාර්ථක විය',
      'hexagonalButtonNextToBox': 'කොටුව අසල ෂඩාස්‍රාකාර බොත්තම',
      'buttonInsideComposeBox': 'සංයුක්ත කොටුව තුළ බොත්තම',
      'swipeCardsToDelete': 'මකා දැමීමට කාඩ්පත් ස්වයිප් කරන්න',
      'longPressForActions': 'ක්‍රියා සඳහා දිගු ඔබන්න',
      'hideIconsOnNoteTaskCards': 'සටහන්/කාර්ය කාඩ්පත්වල අයිකන සඟවන්න',
      'showIconsOnNoteTaskCards': 'සටහන්/කාර්ය කාඩ්පත්වල අයිකන පෙන්වන්න',
      'trueBlackBackground': 'සත්‍ය කළු පසුබිම',
      'useWallpaperColors': 'බිතුපත් වර්ණ භාවිතා කරන්න',
      'customColorScheme': 'අභිරුචි වර්ණ සැලැස්ම',
      'goDirectlyToHomeOnLaunch': 'විවෘත කළ විට කෙලින්ම මුල් පිටුවට යන්න',
      'checkForUpdates': 'යාවත්කාලීන පරීක්ෂා කරන්න',
      'checkingForUpdates': 'යාවත්කාලීන පරීක්ෂා කරමින්...',
      'failedToCheckForUpdates': 'යාවත්කාලීන පරීක්ෂා කිරීම අසාර්ථක විය',
      'download': 'බාගන්න',
      'youAreUsingLatestVersion': 'ඔබ නවතම අනුවාදය භාවිතා කරයි',
      'joinTelegramGroup': 'ටෙලිග්‍රෑම් කණ්ඩායමට එක්වන්න',
      'getSupportAndUpdates': 'සහාය සහ යාවත්කාලීන ලබා ගන්න',
      'supportTheDeveloper': 'සංවර්ධකයාට සහාය දක්වන්න',
      'suggestAFeature': 'විශේෂාංගයක් යෝජනා කරන්න',
      'deleteAllDataConfirmation': 'මෙම ක්‍රියාව ආපසු හැරවිය නොහැක. ඔබගේ සියලු සිතුවිලි සහ කාර්ය ස්ථිරව මකා දමනු ඇත.',
      'myOrdoData': 'මගේ Ordo දත්ත',
      'updateAvailable': 'යාවත්කාලීනයක් තිබේ',
      'from': 'සිට',
      'craftedBy': 'විසින් නිර්මාණය කරන ලදී',
      'madeInLibya': 'ලිබියාවේ නිෂ්පාදිත',
      'softwareDeveloperBuildingOrdo': 'Ordo ගොඩනඟන මෘදුකාංග සංවර්ධකයා.',
      'gitHubProfile': 'GitHub පැතිකඩ',
      'chats': 'කතාබස්',
      'deleteChatTitle': 'කතාබස මකන්නද?',
      'deleteChatMessage': 'මෙය මෙම කතාබස සහ එහි සියලු පණිවිඩ ස්ථිරව මකා දමයි.',
      'startNewConversationHint': 'පහත බොත්තම එබීමෙන්\nනව සංවාදයක් ආරම්භ කරන්න',
      'justNow': 'දැන්',
      'minutesAgo': 'මිනිත්තු {minutes}කට පෙර',
      'hoursAgo': 'පැය {hours}කට පෙර',
      'daysAgo': 'දින {days}කට පෙර',
      'active': 'සක්‍රිය',
      'deleteChatTooltip': 'කතාබස මකන්න',
      'deleteThoughtTitle': 'සිතුවිල්ල මකන්නද?',
      'deleteThoughtMessage': 'මෙම ක්‍රියාව ආපසු හැරවිය නොහැක.',
      'editThought': 'සිතුවිල්ල සංස්කරණය කරන්න',
      'save': 'සුරකින්න',
      'markIncomplete': 'අසම්පූර්ණ ලෙස සලකුණු කරන්න',
      'markComplete': 'සම්පූර්ණ ලෙස සලකුණු කරන්න',
      'setReminder': 'මතක් කිරීමක් සකසන්න',
      'copyText': 'පෙළ පිටපත් කරන්න',
      'labelTask': 'කාර්ය',
      'labelNote': 'සටහන',
      'emptySpaceTitle': 'ඔබේ ඉඩ හිස්ය',
      'emptySpaceMessage': 'පහත සටහනක් හෝ කාර්යයක් ලියා ආරම්භ කිරීමට යවන්න ඔබන්න.',
      'typeThoughtHint': 'සිතුවිල්ලක් ලියන්න...',
      'addTaskHint': 'කාර්යයක් එක් කරන්න...',
      'enterChatNameHint': 'කතාබස් නම ඇතුළත් කරන්න...',
      'suggestions': 'යෝජනා',
      'createChat': 'කතාබස් සාදන්න',
      'setReminderTitle': 'මතක් කිරීමක් සකසන්න',
      'setReminderMessage': 'මෙම කාර්යය ගැන මතක් කිරීමට අවශ්‍ය වේලාව තෝරන්න',
      'skip': 'මඟ හරින්න',
      'setReminderButton': 'මතක් කිරීමක් සකසන්න',
      'suggestionMyThoughts': 'මගේ සිතුවිලි',
      'suggestionDailyTasks': 'දෛනික කාර්ය',
      'suggestionProjectIdeas': 'ව්‍යාපෘති අදහස්',
      'suggestionPersonalNotes': 'පුද්ගලික සටහන්',
      'suggestionWorkJournal': 'වැඩ දිනපොත',
    },
    'pl': {
      'appName': 'ordo',
      'settings': 'Ustawienia',
      'support': 'Pomoc',
      'buyMeACoffee': 'Postaw mi kawę',
      'data': 'Dane',
      'dataExport': 'Eksport danych',
      'dataImport': 'Import danych',
      'preferences': 'Preferencje',
      'darkTheme': 'Tryb ciemny',
      'notifications': 'Powiadomienia',
      'taskReminders': 'Przypomnienia o zadaniach',
      'separateSendButton': 'Oddzielny przycisk wysyłania',
      'swipeToDelete': 'Przesuń, aby usunąć',
      'compactCards': 'Kompaktowe karty',
      'amoledMode': 'Tryb AMOLED',
      'dynamicColor': 'Dynamiczny kolor',
      'specialTheme': 'Specjalny motyw',
      'skipWelcome': 'Pomiń powitanie',
      'deleteAllData': 'Usuń wszystkie dane',
      'deleteAllDataSubtitle': 'Trwale usuń wszystkie notatki i zadania',
      'language': 'Język',
      'system': 'System',
      'english': 'English',
      'arabic': 'العربية',
      'notes': 'notatki',
      'tasks': 'zadania',
      'chat': 'Czat',
      'typeAMessage': 'Napisz wiadomość...',
      'send': 'Wyślij',
      'cancel': 'Anuluj',
      'confirm': 'Potwierdź',
      'ok': 'OK',
      'home': 'Strona główna',
      'noChatsYet': 'Brak czatów',
      'newChat': 'Nowy czat',
      'dangerZone': 'Strefa niebezpieczna',
      'reportAnIssue': 'Zgłoś problem',
      'delete': 'Usuń',
      'allDataDeleted': 'Wszystkie dane zostały usunięte.',
      'failedToExportData': 'Nie udało się wyeksportować danych',
      'importDataTitle': 'Importować dane?',
      'importDataMessage': 'Spowoduje to dodanie wiadomości z poprzednio wyeksportowanego pliku do bieżącego czatu.',
      'importLabel': 'Importuj',
      'dataImportedSuccessfully': 'Dane zaimportowane pomyślnie',
      'noExportFileFound': 'Nie znaleziono pliku eksportu',
      'failedToImportData': 'Nie udało się zaimportować danych',
      'hexagonalButtonNextToBox': 'Sześciokątny przycisk obok pola',
      'buttonInsideComposeBox': 'Przycisk wewnątrz pola kompozycji',
      'swipeCardsToDelete': 'Przesuń karty, aby usunąć',
      'longPressForActions': 'Przytrzymaj, aby wyświetlić działania',
      'hideIconsOnNoteTaskCards': 'Ukryj ikony na kartach notatek/zadań',
      'showIconsOnNoteTaskCards': 'Pokaż ikony na kartach notatek/zadań',
      'trueBlackBackground': 'Prawdziwie czarne tło',
      'useWallpaperColors': 'Użyj kolorów tapety',
      'customColorScheme': 'Niestandardowa kolorystyka',
      'goDirectlyToHomeOnLaunch': 'Przejdź bezpośrednio do strony głównej po uruchomieniu',
      'checkForUpdates': 'Sprawdź aktualizacje',
      'checkingForUpdates': 'Sprawdzanie aktualizacji...',
      'failedToCheckForUpdates': 'Nie udało się sprawdzić aktualizacji',
      'download': 'Pobierz',
      'youAreUsingLatestVersion': 'Używasz najnowszej wersji',
      'joinTelegramGroup': 'Dołącz do grupy Telegram',
      'getSupportAndUpdates': 'Uzyskaj pomoc i aktualizacje',
      'supportTheDeveloper': 'Wesprzyj programistę',
      'suggestAFeature': 'Zaproponuj funkcję',
      'deleteAllDataConfirmation': 'Tej czynności nie można cofnąć. Wszystkie twoje myśli i zadania zostaną trwale usunięte.',
      'myOrdoData': 'Moje dane Ordo',
      'updateAvailable': 'Dostępna aktualizacja',
      'from': 'od',
      'craftedBy': 'Stworzone przez',
      'madeInLibya': 'Wykonane w Libii',
      'softwareDeveloperBuildingOrdo': 'Programista budujący Ordo.',
      'gitHubProfile': 'Profil GitHub',
      'chats': 'Czaty',
      'deleteChatTitle': 'Usunąć czat?',
      'deleteChatMessage': 'Spowoduje to trwałe usunięcie tego czatu i wszystkich jego wiadomości.',
      'startNewConversationHint': 'Rozpocznij nową rozmowę\nnaciskając przycisk poniżej',
      'justNow': 'Przed chwilą',
      'minutesAgo': '{minutes} min temu',
      'hoursAgo': '{hours} godz temu',
      'daysAgo': '{days} dni temu',
      'active': 'Aktywny',
      'deleteChatTooltip': 'Usuń czat',
      'deleteThoughtTitle': 'Usunąć myśl?',
      'deleteThoughtMessage': 'Tej czynności nie można cofnąć.',
      'editThought': 'Edytuj myśl',
      'save': 'Zapisz',
      'markIncomplete': 'Oznacz jako nieukończone',
      'markComplete': 'Oznacz jako ukończone',
      'setReminder': 'Ustaw przypomnienie',
      'copyText': 'Kopiuj tekst',
      'labelTask': 'ZADANIE',
      'labelNote': 'NOTATKA',
      'emptySpaceTitle': 'Twoja przestrzeń jest pusta',
      'emptySpaceMessage': 'Napisz notatkę lub zadanie poniżej i naciśnij wyślij, aby rozpocząć.',
      'typeThoughtHint': 'Napisz myśl...',
      'addTaskHint': 'Dodaj zadanie...',
      'enterChatNameHint': 'Wprowadź nazwę czatu...',
      'suggestions': 'Sugestie',
      'createChat': 'Utwórz czat',
      'setReminderTitle': 'Ustaw przypomnienie',
      'setReminderMessage': 'Wybierz, kiedy chcesz otrzymać przypomnienie o tym zadaniu',
      'skip': 'Pomiń',
      'setReminderButton': 'Ustaw przypomnienie',
      'suggestionMyThoughts': 'Moje myśli',
      'suggestionDailyTasks': 'Codzienne zadania',
      'suggestionProjectIdeas': 'Pomysły na projekty',
      'suggestionPersonalNotes': 'Osobiste notatki',
      'suggestionWorkJournal': 'Dziennik pracy',
    },
  };

  String? operator [](String key) {
    final tag = locale.toLanguageTag();
    return _strings[tag]?[key] ?? _strings[locale.languageCode]?[key] ?? _strings['en']?[key];
  }

  String translate(String key) => this[key] ?? key;
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['en', 'ar', 'ru', 'ko', 'fa', 'es', 'id', 'vi', 'zh',
       'es-MX', 'pt-BR', 'fil', 'ur', 'si', 'pl'].contains(locale.toLanguageTag());

  @override
  Future<AppLocalizations> load(Locale locale) =>
      Future.value(AppLocalizations(locale));

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
